import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ToastContainer } from "react-toastify";
import NextAuthProvider from "@/Provider/NextAuthProvider";
import Container from "@/components/Container";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//my website font
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});
export const metadata = {
  title: "Bike",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} $ antialiased`}>
        <NextAuthProvider>
          <Navbar />

          <div className="min-h-[calc(100vh-472px)]">
            <Container>
              <main>{children}</main>
            </Container>
            <ToastContainer position="top-right" />
          </div>

          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
